name: GitHub Organization Stats
description: ""
# branding:
#   icon: "database"
#   color: green
inputs:
  org:
    description: "GitHub organization login"
    required: true
  path:
    description: "Relative path to .csv file (example: data/stats.csv)"
    required: true
outputs:
  data:
    description: "stats as JSON string"
runs:
  using: "node16"
  main: "dist/index.js"
