# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 12 * * 1,5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # logOctokitStats:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/githubmergechecker
  #       id: stats
  #       with:
  #         org: springroll
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - run: |
  #         cat << EOF
  #         result: ${{ steps.stats.outputs.data }}
  #         EOF
  updateOctokitStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/githubmergechecker
        id: stats
        with:
          org: springroll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # append stats to data/octokit.csv
      - uses: gr2m/write-csv-file-action@v1.0.4
        with:
          path: data/octokit.csv
          columns: repository name,weeks since main merge,weeks since dev merge
          "repository name": ${{ fromJson(steps.stats.outputs.data).name }}
          # "weeks since main merge": ${{ fromJson(steps.stats.outputs.data).weeksSinceMainBranchMerge }}
          # "weeks since dev merge": ${{ fromJson(steps.stats.outputs.data).weeksSinceDevBranchMerge }}
      # push updated file back to main branch
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add data
      - run: git commit -m "data/octokit.csv updated"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}